spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/releasescribe
    username: releasescribe
    password: releasescribe

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: releasescribe
    password: releasescribe